package com.slf.engine.bo;


import java.math.BigDecimal;

import com.slf.engine.base.BaseObj;

public class LsMtsms extends BaseObj {
	private String startDate;
	private String endDate;
	
    public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DXID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private Long dxid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DLID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String jrbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String dlflsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.PCH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String pch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.YYS
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String yys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.JG
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private BigDecimal jg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.TDBH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String tdbh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSHM
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fshm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSNR
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fsnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fsrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String fhsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.ZT
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    private String zt;
    private int temp_zt;
    
    private String fhxx;
    
    

    public String getFhxx() {
		return fhxx;
	}

	public void setFhxx(String fhxx) {
		this.fhxx = fhxx;
	}

	public int getTemp_zt() {
		return temp_zt;
	}

	public void setTemp_zt(int temp_zt) {
		this.temp_zt = temp_zt;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DXID
     *
     * @return the value of LS_MTSMS.DXID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public Long getDxid() {
        return dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DXID
     *
     * @param dxid the value for LS_MTSMS.DXID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setDxid(Long dxid) {
        this.dxid = dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DLID
     *
     * @return the value of LS_MTSMS.DLID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DLID
     *
     * @param dlid the value for LS_MTSMS.DLID
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.JRBZ
     *
     * @return the value of LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getJrbz() {
        return jrbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.JRBZ
     *
     * @param jrbz the value for LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setJrbz(String jrbz) {
        this.jrbz = jrbz == null ? null : jrbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DLFLSH
     *
     * @return the value of LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getDlflsh() {
        return dlflsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DLFLSH
     *
     * @param dlflsh the value for LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setDlflsh(String dlflsh) {
        this.dlflsh = dlflsh == null ? null : dlflsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.PCH
     *
     * @return the value of LS_MTSMS.PCH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getPch() {
        return pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.PCH
     *
     * @param pch the value for LS_MTSMS.PCH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setPch(String pch) {
        this.pch = pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.YYS
     *
     * @return the value of LS_MTSMS.YYS
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getYys() {
        return yys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.YYS
     *
     * @param yys the value for LS_MTSMS.YYS
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setYys(String yys) {
        this.yys = yys == null ? null : yys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.JG
     *
     * @return the value of LS_MTSMS.JG
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public BigDecimal getJg() {
        return jg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.JG
     *
     * @param jg the value for LS_MTSMS.JG
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setJg(BigDecimal jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.TDBH
     *
     * @return the value of LS_MTSMS.TDBH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.TDBH
     *
     * @param tdbh the value for LS_MTSMS.TDBH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSH
     *
     * @return the value of LS_MTSMS.FSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFsh() {
        return fsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSH
     *
     * @param fsh the value for LS_MTSMS.FSH
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFsh(String fsh) {
        this.fsh = fsh == null ? null : fsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSHM
     *
     * @return the value of LS_MTSMS.FSHM
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFshm() {
        return fshm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSHM
     *
     * @param fshm the value for LS_MTSMS.FSHM
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFshm(String fshm) {
        this.fshm = fshm == null ? null : fshm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSNR
     *
     * @return the value of LS_MTSMS.FSNR
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFsnr() {
        return fsnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSNR
     *
     * @param fsnr the value for LS_MTSMS.FSNR
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFsnr(String fsnr) {
        this.fsnr = fsnr == null ? null : fsnr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSRQ
     *
     * @return the value of LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFsrq() {
        return fsrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSRQ
     *
     * @param fsrq the value for LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFsrq(String fsrq) {
        this.fsrq = fsrq == null ? null : fsrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSSJ
     *
     * @return the value of LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFssj() {
        return fssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSSJ
     *
     * @param fssj the value for LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFssj(String fssj) {
        this.fssj = fssj == null ? null : fssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FHSJ
     *
     * @return the value of LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getFhsj() {
        return fhsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FHSJ
     *
     * @param fhsj the value for LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setFhsj(String fhsj) {
        this.fhsj = fhsj == null ? null : fhsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.ZT
     *
     * @return the value of LS_MTSMS.ZT
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.ZT
     *
     * @param zt the value for LS_MTSMS.ZT
     *
     * @ibatorgenerated Fri Feb 01 11:35:00 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }
}